### ISSUE TITLE
Rehosting of data

### ISSUE THREAD

**Issue by Prunoideae** [kimpenn/VisCello.celegans#7]
Currently, LFS bandwidth is capped at 1GB/month, but the total LFS objects in the repository are over 800MB, causing it unavailable for anyone who wants to clone the data if any clone is done in the same month.

```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/kimpenn/VisCello.celegans.git/info/lfs'
```

Is it possible to rehost the data folder somewhere else, like MEGA or Google Drive? Thanks in advance.

**Comment by qinzhu** [comment]
Sorry for the delayed response, you can now get it from Zenodo: https://zenodo.org/record/8397398.
